---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
  name: tor
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: clab-bgp-cplane-devel-control-plane
  virtualRouters:
  - localASN: 65001
    exportPodCIDR: false
    serviceSelector:
      matchLabels:
        color: green
      matchExpressions:
        - {key: io.kubernetes.service.namespace, operator: In, values: ["tenant-b"]}
    neighbors:
    - peerAddress: "172.0.0.1/32"
      peerASN: 65000

      